module.exports = {
    staff:[
        {
            name: ['张亚杰', 'JASON'],
            profile: "../../../img/profile/zhangyajie.jpg",
            role: ['首席执行官', 'FOUNDER'],
            title: 'CEO & President',
            description: ['毕业于Frank·Zarb School of Business, 本科毕业于中山大学', 
            '人类学背景，曾背包游历过三大洲、N个国家做田野，对于旅行有着浓厚的兴趣。曾就职于美国政府机构、天津汇方有限公司，在汇方有限公司期间任项目开发部经理&总裁助理',
            '橙子态度：人生就像一场“旅橙”，让我在时间与空间里寻找意义。 '],
        },
        {
            name: ['蒋宏达', 'JOHN'],
            profile: "../../../img/profile/jianghongda.jpeg",
            role: ['软件工程师', 'FOUNDER'],
            title: 'Software Engineer  & Founder',
            description: ['毕业于New York University，本科毕业于中山大学', 
            '雅虎软件工程师',
            '橙子态度：享受路上的风景，回忆路上的人。'],
        },
        {
            name: ['胡心远', 'ALEX'],
            profile: "../../../img/profile/huxinyuan.jpeg",
            role: ['软件工程师', 'FOUNDER'],
            title: 'Software Engineer & Founder',
            description: ['毕业于New York University，本科毕业于复旦大学', 
            'Google软件工程师',
            '橙子态度：放空自己，玩得飞起！'],
        },
        {
            name: ['潘安琪', 'ANGEL'],
            profile: "../../../img/profile/pananqi.jpeg",
            role: ['加州拓展专员', 'FOUNDER'],
            title: 'CA Branch Developer & Founder',
            description: ['现就读于Santa Clara University，本科毕业于上海外国语大学', 
            '曾就职于Tiffany & Co市场部。',
            '橙子态度：还有那么多回忆与美景，等着我去欣赏与探寻。'],
        },
        {
            name: ['宁可方'],
            profile: "../../../img/profile/ningkefang.jpeg",
            role: ['设计师'],
            title: 'Designer',
            description: ['毕业于New school, Parsons the school for Design, 本科毕业于中国人民大学', 
            '曾就职于微软、人人网',
            '橙子态度：吃西柚不剥皮'],
        },
        {
            name: ['刘琋'],
            profile: "../../../img/profile/liuxi.jpg",
            role: ['软件工程师', 'FOUNDER'],
            title: 'Software Engineer & Founder',
            description: ['现就读于New York University，本科毕业于中山大学', 
            '出版过游记，拿过国奖，领过专利，当过校电视台主播，做过游戏电台主播，参加过亚运开幕式演出，励志当一枚闯入设计圈的创客',
            '橙子态度：Go out in the world and embrace it beautifully.'],
        },
        {
            name: ['杜玮'],
            profile: "../../../img/profile/duwei.jpeg",
            role: ['设计师'],
            title: 'Designer',
            description: ['毕业于University of Southern California, 本科毕业于西北农林科技大学', 
            '曾就职于洛杉矶市公园游憩局 City of Los Angeles Department of Recreation and Park',
            '橙子态度：Design is the privilege of life. 在路上，不要停'],
        },
        {
            name: ['莫涛'],
            profile: "../../../img/profile/motao.jpeg",
            role: ['运营部，旅游产品设计师'],
            title: 'Operation Department, Travel Products Designer',
            description: ['就读于Columbia University，本科毕业于清华大学', 
            '曾就职于花旗银行',
            '橙子态度：既然选择了远方，便只顾风雨兼程。'],
        },
        {
            name: ['纳思奇'],
            profile: "../../../img/profile/nasiqi.jpeg",
            role: ['运营部，旅游产品设计师'],
            title: 'Operation Department, Travel Products Designer',
            description: ['毕业于Oklahoma State University, 本科毕业于中山大学', 
            '橙子态度：生命，不长不短，刚好够用来好好看看这个世界。'],
        },
        {
            name: ['周蜜'],
            profile: "../../../img/profile/zhoumi.jpeg",
            role: ['市场部，市场专员'],
            title: 'Marketing Department, Marketing Generalist',
            description: ['毕业于Syracuse University, 本科毕业于南京师范大学', 
            '曾就职于搜狐网',
            '橙子态度:  在旅程中，遇见真正的自己'],
        },
        {
            name: ['韩筱竹'],
            profile: "../../../img/profile/hanxiaozhu.png",
            role: ['市场部，市场专员'],
            title: 'Marketing department, Marketing Generalist',
            description: ['毕业于Hofstra University, 本科毕业于台湾中原大学', 
            '曾就职于台湾政府机构',
            '橙子态度: 旅行的美妙之处在于它的过程, 不仅仅是沿途的风景, 每趟旅行都让我们的阅历更加丰富宽广'],
        },
        {
            name: ['王妍'],
            profile: "../../../img/profile/wangyan.jpeg",
            role: ['市场部，公共关系专员'],
            title: 'Marketing Department, PR Coordinator',
            description: ['毕业于Kent State University，本科毕业于上海外国语大学', 
            '侨报编辑，曾就职于CIMB香港投行部、北京中信银行',
            '橙子态度：看看世界有多大，才知自己有多小。'],
        },
        {
            name: ['杨程'],
            profile: "../../../img/profile/yangcheng.jpeg",
            role: ['市场部，主编'],
            title: 'Marketing Department, Editor',
            description: ['毕业于Hofstra University，本科毕业于天津商业大学', 
            '曾就职于王朝御苑酒堡',
            '橙子态度：只愿走过再多的路，依旧看山是山，看水是水'],
        },
        {
            name: ['欧阳倩威'],
            profile: "../../../img/profile/ouyangqianwei.jpeg",
            role: ['市场部，文案&编辑'],
            title: 'Marketing Department, Editor',
            description: ['现就读于Fordham University，本科毕业于上海财经大学', 
            '曾就职于LVMH Fashion Group',
            '橙子态度：要有读万卷书的执着，更要有行万里路的勇敢。'],
        },
        {
            name: ['刘志强'],
            profile: "../../../img/profile/liuzhiqiang.jpeg",
            role: ['市场部，文案&编辑'],
            title: 'Marketing Department, Editor',
            description: ['现就读于New York University，本科毕业于华中科技大学', 
            '曾就职于The Home Depot (Supply Chain Associate ), Mobotap Inc. ',
            '橙子态度：心怀好奇与敬畏，看世界之瑰奇'],
        },
        {
            name: ['王至晨'],
            profile: "../../../img/profile/wangzhichen.jpeg",
            role: ['市场部，文案&编辑'],
            title: 'Marketing Department, Editor',
            description: ['毕业于University of Michigan, Ann Arbor，本科毕业于中山大学', 
            '曾就职于Logic Solutions, Inc.(Finance/Accounting Assistant), Burns & Wilcox(Specialty Insurance Assistant)',
            '橙子态度：旅行不是件容易的事，能把它做好的人更不容易！'],
        },
        {
            name: ['姜星'],
            profile: "../../../img/profile/jiangxin.jpg",
            role: ['人力资源部，人力资源主管'],
            title: 'HR Department, Manager of HR Department',
            description: ['毕业于Hofstra University, 本科毕业于浙江师范大学', 
            '曾任SHRM-Hofstra Student Chapter 副主席',
            '橙子态度：体验不一样的旅程，领略不一样的风景，感受不一样的自己。'],
        },
        {
            name: ['郭若舟'],
            profile: "../../../img/profile/guoruozhou.jpeg",
            role: ['财务，顾问'],
            title: 'Accounting Consultant',
            description: ['毕业于Hofstra University', 
            'Ernst & Young(Tax Staff)'],
        },
    ]
    
    
}